# Generated by Django 4.0.3 on 2022-03-16 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgLegalType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_column='Title', max_length=250)),
                ('value', models.CharField(db_column='Value', max_length=250)),
            ],
        ),
        migrations.AlterField(
            model_name='cleandata',
            name='org_legaltype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cd_org_legaltype', to='home.orglegaltype'),
        ),
        migrations.AlterField(
            model_name='dump',
            name='org_legaltype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='org_legaltype', to='home.orglegaltype'),
        ),
    ]
