# Generated by Django 4.0.3 on 2023-03-06 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(blank=True, max_length=250, null=True)),
                ('description1', models.TextField(blank=True, max_length=2050, null=True)),
                ('description1_url', models.CharField(blank=True, max_length=250, null=True)),
                ('map_description', models.TextField(blank=True, max_length=1050, null=True)),
                ('title2', models.CharField(blank=True, max_length=250, null=True)),
                ('description2', models.TextField(blank=True, max_length=2050, null=True)),
                ('disclaimer', models.TextField(blank=True, max_length=2050, null=True)),
                ('access_form_url', models.CharField(blank=True, max_length=250, null=True)),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('future_use1', models.CharField(blank=True, max_length=250, null=True)),
                ('future_use2', models.CharField(blank=True, max_length=250, null=True)),
                ('future_use3', models.TextField(blank=True, max_length=2050, null=True)),
                ('upsrt_dttm', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrgDetailsPageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('future_use1', models.CharField(blank=True, max_length=250, null=True)),
                ('future_use2', models.CharField(blank=True, max_length=250, null=True)),
                ('future_use3', models.TextField(blank=True, max_length=2050, null=True)),
                ('upsrt_dttm', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrgLegalType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_column='Title', max_length=250)),
                ('value', models.CharField(db_column='Value', max_length=250)),
                ('upsrt_dttm', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('value',),
            },
        ),
        migrations.CreateModel(
            name='PartnerLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_img', models.ImageField(blank=True, null=True, upload_to='')),
                ('type', models.CharField(blank=True, max_length=20, null=True)),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('additional_text', models.CharField(blank=True, max_length=250, null=True)),
                ('upsrt_dttm', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TargetCommunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_column='Title', max_length=250)),
                ('value', models.CharField(db_column='Value', max_length=250)),
                ('exclude_from_filter', models.BooleanField(default=False)),
                ('upsrt_dttm', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('value',),
            },
        ),
        migrations.AlterModelOptions(
            name='cleandata',
            options={'ordering': ('org_name',)},
        ),
        migrations.AlterModelOptions(
            name='dump',
            options={'ordering': ('org_name',)},
        ),
        migrations.AlterModelOptions(
            name='geographicscope',
            options={'ordering': ('value',)},
        ),
        migrations.AlterModelOptions(
            name='orgtype',
            options={'ordering': ('value',)},
        ),
        migrations.AlterModelOptions(
            name='settlement',
            options={'ordering': ('value',)},
        ),
        migrations.AlterModelOptions(
            name='targetdemographic',
            options={'ordering': ('value',)},
        ),
        migrations.AlterModelOptions(
            name='thematicarea',
            options={'ordering': ('value',)},
        ),
        migrations.RenameField(
            model_name='cleandata',
            old_name='org_offices',
            new_name='org_primary_technical_area_focus',
        ),
        migrations.RenameField(
            model_name='cleandata',
            old_name='refugee_zone',
            new_name='respondent_email_address',
        ),
        migrations.RenameField(
            model_name='dump',
            old_name='org_offices',
            new_name='org_primary_technical_area_focus',
        ),
        migrations.RenameField(
            model_name='dump',
            old_name='refugee_zone',
            new_name='org_targetgroup_other',
        ),
        migrations.RemoveField(
            model_name='cleandata',
            name='org_activities',
        ),
        migrations.RemoveField(
            model_name='cleandata',
            name='org_primarytechnicalarea',
        ),
        migrations.RemoveField(
            model_name='cleandata',
            name='org_secondarytechnicalarea1',
        ),
        migrations.RemoveField(
            model_name='cleandata',
            name='org_secondarytechnicalarea2',
        ),
        migrations.RemoveField(
            model_name='cleandata',
            name='refugee_settlement',
        ),
        migrations.RemoveField(
            model_name='dump',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='dump',
            name='org_activities',
        ),
        migrations.RemoveField(
            model_name='dump',
            name='org_code',
        ),
        migrations.RemoveField(
            model_name='dump',
            name='org_primarytechnicalarea',
        ),
        migrations.RemoveField(
            model_name='dump',
            name='org_secondarytechnicalarea1',
        ),
        migrations.RemoveField(
            model_name='dump',
            name='org_secondarytechnicalarea2',
        ),
        migrations.RemoveField(
            model_name='dump',
            name='refugee_settlement',
        ),
        migrations.AddField(
            model_name='cleandata',
            name='associated_settlements',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='cleandata',
            name='associated_thematic_areas',
            field=models.TextField(blank=True, max_length=1250, null=True),
        ),
        migrations.AddField(
            model_name='cleandata',
            name='logo_img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='cleandata',
            name='other_actors_in_settlement',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='cleandata',
            name='respondent_job_title',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='cleandata',
            name='respondent_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='cleandata',
            name='respondent_telephone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cleandata',
            name='settlement_operation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cleandata',
            name='total_num_of_staff',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cleandata',
            name='upsrt_dttm',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='cleandata',
            name='uuid',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='dump',
            name='associated_settlements',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='dump',
            name='associated_thematic_areas',
            field=models.TextField(blank=True, max_length=1250, null=True),
        ),
        migrations.AddField(
            model_name='dump',
            name='logo_img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='dump',
            name='org_legaltype_other',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dump',
            name='org_targetdemographic_other',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='dump',
            name='org_type_other',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dump',
            name='other_actors_in_settlement',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='dump',
            name='respondent_email_address',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='dump',
            name='respondent_job_title',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='dump',
            name='respondent_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='dump',
            name='respondent_telephone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dump',
            name='settlement_operation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dump',
            name='total_num_of_staff',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dump',
            name='upsrt_dttm',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='dump',
            name='uuid',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='orgtype',
            name='exclude_from_filter',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='orgtype',
            name='upsrt_dttm',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='settlement',
            name='upsrt_dttm',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='targetdemographic',
            name='exclude_from_filter',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='targetdemographic',
            name='upsrt_dttm',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='thematicarea',
            name='exclude_from_filter',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='thematicarea',
            name='upsrt_dttm',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='cleandata',
            name='org_acronym',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cleandata',
            name='org_legaltype',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='cleandata',
            name='org_targetdemographic',
        ),
        migrations.AddField(
            model_name='cleandata',
            name='org_targetdemographic',
            field=models.ManyToManyField(blank=True, null=True, related_name='cd_org_targetdemographic', to='home.targetdemographic'),
        ),
        migrations.AlterField(
            model_name='dump',
            name='org_acronym',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dump',
            name='org_legaltype',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dump',
            name='org_targetdemographic',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='dump',
            name='org_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='SettlementOrgAssociation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zones', models.TextField(blank=True, max_length=1000, null=True)),
                ('operation_offices', models.TextField(blank=True, max_length=1000, null=True)),
                ('num_of_staffs', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('upsrt_dttm', models.DateTimeField(auto_now=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_settlement', to='home.cleandata')),
                ('primary_thematic_area', models.ManyToManyField(blank=True, null=True, related_name='settlement_primary_thematic_area', to='home.thematicarea')),
                ('settlement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlement_org', to='home.settlement')),
            ],
        ),
        migrations.CreateModel(
            name='DumpSettlements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settlement', models.CharField(blank=True, max_length=120, null=True)),
                ('primary_thematic_area', models.CharField(blank=True, max_length=250, null=True)),
                ('zones', models.CharField(blank=True, max_length=250, null=True)),
                ('operation_offices', models.TextField(blank=True, max_length=1000, null=True)),
                ('num_of_staffs', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('upsrt_dttm', models.DateTimeField(auto_now=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dump_settlement', to='home.dump')),
            ],
        ),
        migrations.CreateModel(
            name='AlternativeLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='')),
                ('logo_url', models.CharField(blank=True, max_length=700, null=True)),
                ('upsrt_dttm', models.DateTimeField(auto_now=True)),
                ('org_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_type_logo', to='home.orgtype')),
            ],
        ),
    ]
