# Generated by Django 4.0.3 on 2022-03-06 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dump',
            name='organisation_name2',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
