# Generated by Django 4.0.3 on 2022-03-06 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_dump_organisation_name2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleandata',
            name='organisation_name',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='cleandata',
            name='organisation_name2',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
