# Generated by Django 4.0.3 on 2022-04-17 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_landingpagecontent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cleandata',
            old_name='refugee_zone',
            new_name='respondent_email_address',
        ),
        migrations.RemoveField(
            model_name='cleandata',
            name='org_activities',
        ),
        migrations.RemoveField(
            model_name='cleandata',
            name='org_offices',
        ),
        migrations.RemoveField(
            model_name='cleandata',
            name='org_primarytechnicalarea',
        ),
        migrations.RemoveField(
            model_name='cleandata',
            name='org_secondarytechnicalarea1',
        ),
        migrations.RemoveField(
            model_name='cleandata',
            name='org_secondarytechnicalarea2',
        ),
        migrations.RemoveField(
            model_name='cleandata',
            name='refugee_settlement',
        ),
        migrations.AddField(
            model_name='cleandata',
            name='org_primary_technical_area_focus',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='cleandata',
            name='other_actors_in_settlement',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='cleandata',
            name='respondent_job_title',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='cleandata',
            name='respondent_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='cleandata',
            name='respondent_telephone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cleandata',
            name='settlement_operation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cleandata',
            name='org_acronym',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cleandata',
            name='org_legaltype',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='SettlementOrgAssociation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zones', models.TextField(blank=True, max_length=1000, null=True)),
                ('operation_offices', models.TextField(blank=True, max_length=1000, null=True)),
                ('num_of_staffs', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_settlement', to='home.cleandata')),
                ('primary_thematic_area', models.ManyToManyField(related_name='settlement_primary_thematic_area', to='home.thematicarea')),
                ('settlement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlement_org', to='home.settlement')),
            ],
        ),
    ]
