# Generated by Django 4.0.3 on 2023-03-06 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_delete_targetcommunity'),
    ]

    operations = [
        migrations.CreateModel(
            name='TargetCommunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_column='Title', max_length=250)),
                ('value', models.CharField(db_column='Value', max_length=250)),
                ('exclude_from_filter', models.BooleanField(default=False)),
                ('upsrt_dttm', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('value',),
            },
        ),
    ]
