# Generated by Django 4.0.3 on 2023-03-06 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_partnertype_alter_partnerlogo_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partnerlogo',
            name='type',
        ),
    ]
