# Generated by Django 4.0.3 on 2022-05-24 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_cleandata_logo_img_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cleandata',
            options={'ordering': ('org_name',)},
        ),
        migrations.AlterModelOptions(
            name='dump',
            options={'ordering': ('org_name',)},
        ),
        migrations.AlterModelOptions(
            name='geographicscope',
            options={'ordering': ('value',)},
        ),
        migrations.AlterModelOptions(
            name='orglegaltype',
            options={'ordering': ('value',)},
        ),
        migrations.AlterModelOptions(
            name='orgtype',
            options={'ordering': ('value',)},
        ),
        migrations.AlterModelOptions(
            name='settlement',
            options={'ordering': ('value',)},
        ),
        migrations.AlterModelOptions(
            name='targetdemographic',
            options={'ordering': ('value',)},
        ),
        migrations.AlterModelOptions(
            name='thematicarea',
            options={'ordering': ('value',)},
        ),
        migrations.AddField(
            model_name='alternativelogo',
            name='upsrt_dttm',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='cleandata',
            name='associated_settlements',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='cleandata',
            name='associated_thematic_areas',
            field=models.TextField(blank=True, max_length=1250, null=True),
        ),
        migrations.AddField(
            model_name='cleandata',
            name='total_num_of_staff',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cleandata',
            name='upsrt_dttm',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='dump',
            name='upsrt_dttm',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='upsrt_dttm',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='orgdetailspagecontent',
            name='upsrt_dttm',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='orglegaltype',
            name='upsrt_dttm',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='orgtype',
            name='upsrt_dttm',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='settlement',
            name='upsrt_dttm',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='settlementorgassociation',
            name='upsrt_dttm',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='targetdemographic',
            name='upsrt_dttm',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='thematicarea',
            name='upsrt_dttm',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='cleandata',
            name='org_targetdemographic',
            field=models.ManyToManyField(blank=True, null=True, related_name='cd_org_targetdemographic', to='home.targetdemographic'),
        ),
        migrations.AlterField(
            model_name='settlementorgassociation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
