# Generated by Django 4.0.3 on 2023-03-13 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_partnerlogo_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleandata',
            name='latitude',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='cleandata',
            name='longitude',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
