# Generated by Django 4.0.3 on 2023-03-20 03:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0013_cleandata_latitude_cleandata_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettlementZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_column='Title', max_length=250)),
                ('value', models.CharField(db_column='Value', max_length=250)),
                ('upsrt_dttm', models.DateTimeField(auto_now=True)),
                ('settlement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlement_zone', to='home.settlement')),
            ],
            options={
                'ordering': ('value',),
            },
        ),
        migrations.CreateModel(
            name='FormSubmissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respondent_name', models.CharField(blank=True, max_length=150, null=True)),
                ('respondent_job_title', models.CharField(blank=True, max_length=250, null=True)),
                ('respondent_email_address', models.CharField(blank=True, max_length=250, null=True)),
                ('respondent_telephone', models.CharField(blank=True, max_length=50, null=True)),
                ('org_name', models.TextField(blank=True, max_length=1000, null=True)),
                ('org_acronym', models.CharField(blank=True, max_length=100, null=True)),
                ('org_email', models.CharField(blank=True, max_length=250, null=True)),
                ('org_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('org_website', models.CharField(blank=True, max_length=250, null=True)),
                ('org_facebook', models.CharField(blank=True, max_length=250, null=True)),
                ('org_twitter', models.CharField(blank=True, max_length=250, null=True)),
                ('org_logo', models.TextField(blank=True, max_length=1250, null=True)),
                ('founding_year', models.CharField(blank=True, max_length=5, null=True)),
                ('years_active', models.CharField(blank=True, max_length=5, null=True)),
                ('org_primarycontact', models.CharField(blank=True, max_length=250, null=True)),
                ('settlement_operation', models.CharField(blank=True, max_length=100, null=True)),
                ('associated_settlements', models.TextField(blank=True, max_length=500, null=True)),
                ('associated_thematic_areas', models.TextField(blank=True, max_length=1250, null=True)),
                ('total_num_of_staff', models.IntegerField(blank=True, null=True)),
                ('org_legaltype', models.TextField(blank=True, null=True)),
                ('org_primary_technical_area_focus', models.TextField(blank=True, max_length=1000, null=True)),
                ('org_targetgroup', models.CharField(blank=True, max_length=250, null=True)),
                ('other_actors_in_settlement', models.CharField(blank=True, max_length=10, null=True)),
                ('contact_name', models.CharField(blank=True, max_length=250, null=True)),
                ('contact_role', models.CharField(blank=True, max_length=150, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('contact_email', models.CharField(blank=True, max_length=150, null=True)),
                ('logo_img', models.ImageField(blank=True, null=True, upload_to='')),
                ('uuid', models.CharField(blank=True, max_length=250, null=True)),
                ('upsrt_dttm', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('org_targetdemographic', models.ManyToManyField(blank=True, null=True, related_name='fs_org_targetdemographic', to='home.targetdemographic')),
                ('org_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fs_org_type', to='home.orgtype')),
            ],
            options={
                'ordering': ('org_name',),
            },
        ),
    ]
