# Generated by Django 4.0.3 on 2023-03-20 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_settlementzone_formsubmissions'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FormSubmissions',
        ),
    ]
