# Generated by Django 4.0.3 on 2023-03-20 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_delete_formsubmissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleandata',
            name='data_source',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='cleandata',
            name='data_status',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
